### ISSUE TITLE
Sagemath and binder do not work together (neither docker nor conda)

### ISSUE THREAD

**Issue by enriqueartal** [sagemath/sage-binder-env#10]
I made several tries to work with sagemath and mybinder with no success:

- Docker with sagemathinc/cocalc:latest used to work, it does not any more for me.
- Tried also with cocalc-lite, same thing.
In both cases basically the same error as in [this post](https://discourse.jupyter.org/t/binder-and-sagemath/11059/2?u=enriqueartal)
I tried the conda approach both the tests and one of my repos (not explained in the readme, just disable docker file and copy environment.yml. In this case binder session is opened but sage kernel is not connected. Running `sage` in the terminal gives the error in [this other post](https://discourse.jupyter.org/t/binder-and-sagemath/11059/9?u=enriqueartal).

**Comment by slel** [comment]
Visiting https://github.com/flatsurf/ipyvue-flatsurf and clicking
the "launch binder" button gives a working Sage 9.6 in Binder.

**Comment by enriqueartal** [comment]
I got Sage 9.5 and it worked. I copied the environment.yml to one of my repos, binder started but no sage

**Comment by enriqueartal** [comment]
It works, I copied the environment.yml file. I get 9.5 instead of 9.6; it complains about missing matplotlib. If I want to see an output I need to use print or show, it is not enough to write the variable at the last line of the cell.
By some reason, cocalc's docker works today

**Comment by saraedum** [comment]
> it complains about missing matplotlib

could you elaborate?

**Comment by saraedum** [comment]
The environment.yml we use at ipyvue-flatsurf uses sagelib 9.5 because some of the dependencies (surface-dynamics) have not been built for 9.6 yet.

**Comment by nthiery** [comment]
I indeed noticed that sage-binder-env was broken currently. I tried a month ago reverting to 9.2 in 98ed8d11,
but to no avail. My best bet was an incompatibility with SageMath packaged with conda with recent underlying
os image. Upon starting Sage, there is a failure:

ImportError: libgsl.so.25: cannot open shared object file: No such file or directory

I did not get however to investigate further, or even report upstream.

**Comment by enriqueartal** [comment]
> > it complains about missing matplotlib
> 
> could you elaborate?

Both in the terminal and in jupyter. If I type `print(1+1)` i get the answer, and also with `show(1+1)`. But with `1+1` i get:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_486/225133317.py in <module>
----> 1 Integer(1)+Integer(1)

/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/displayhook.py in __call__(self, result)
    260             self.start_displayhook()
    261             self.write_output_prompt()
--> 262             format_dict, md_dict = self.compute_format_data(result)
    263             self.update_user_ns(result)
    264             self.fill_exec_result(result)

/srv/conda/envs/notebook/lib/python3.7/site-packages/IPython/core/displayhook.py in compute_format_data(self, result)
    149 
    150         """
--> 151         return self.shell.display_formatter.format(result)
    152 
    153     # This can be set to True by the write_output_prompt method in a subclass

/srv/conda/envs/notebook/lib/python3.7/site-packages/sage/repl/display/formatter.py in format(self, obj, include, exclude)
    184         # use Sage rich output for any except those native to IPython, but only
    185         # if it is not plain and dull
--> 186         if (not isinstance(obj, (IPYTHON_NATIVE_TYPES, Figure)) and
    187             not set(sage_format.keys()).issubset([PLAIN_TEXT])):
    188             return sage_format, sage_metadata

/srv/conda/envs/notebook/lib/python3.7/site-packages/sage/misc/lazy_import.pyx in sage.misc.lazy_import.LazyImport.__instancecheck__ (build/cythonized/sage/misc/lazy_import.c:7695)()
    914             True
    915         """
--> 916         return isinstance(x, self.get_object())
    917 
    918     def __subclasscheck__(self, x):

/srv/conda/envs/notebook/lib/python3.7/site-packages/sage/misc/lazy_import.pyx in sage.misc.lazy_import.LazyImport.get_object (build/cythonized/sage/misc/lazy_import.c:2612)()
    215         if likely(self._object is not None):
    216             return self._object
--> 217         return self._get_object()
    218 
    219     cpdef _get_object(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/sage/misc/lazy_import.pyx in sage.misc.lazy_import.LazyImport._get_object (build/cythonized/sage/misc/lazy_import.c:3073)()
    255             if self._feature:
    256                 raise FeatureNotPresentError(self._feature, reason=f'Importing {self._name} failed: {e}')
--> 257             raise
    258 
    259         name = self._as_name

/srv/conda/envs/notebook/lib/python3.7/site-packages/sage/misc/lazy_import.pyx in sage.misc.lazy_import.LazyImport._get_object (build/cythonized/sage/misc/lazy_import.c:2935)()
    251 
    252         try:
--> 253             self._object = getattr(__import__(self._module, {}, {}, [self._name]), self._name)
    254         except ImportError as e:
    255             if self._feature:

ModuleNotFoundError: No module named 'matplotlib'

**Comment by saraedum** [comment]
@enriqueartal do you have a link to the repository that does not work for you?

**Comment by enriqueartal** [comment]
> @enriqueartal do you have a link to the repository that does not work for you?

The repository was https://github.com/enriqueartal/TorsionDivisorsCubicZariskiPairs, branch sagedev. With your new environment.yml it works. I got errors in some notebooks since they were built for previous versions of sage. Actually it would be helpful for me to install optional packages for sage (sirocco and for other notebooks gap_packages). Sorry for a newby question, how can it be done? Anyway, thanks for the solution!
