### ISSUE TITLE
Unable to install a package

### ISSUE THREAD

**Issue by enriqueartal** [sagemath/sage-binder-env#18]
I tried to install a package, sirocco, and I got this. 
```
Step 17/24 : RUN /sage/sage -i sirocco
 ---> Running in 8c950112eff7
/sage/src/bin/sage: line 226: /sage/build/bin/sage-site: No such file or directory
```
After commenting the line of installing I checked that the folder build does not exist. Without installing the package, it works really nice and fast. Best, Enrique

**Comment by enriqueartal** [comment]
The same issue with 10.3beta0

**Comment by kwankyu** [comment]
Right. It won't work now.

The sage delivered by the Dockerfile is a version stripped off all configuration and build facilities (and also the documentation), to reduce the Docker image size as far as possible. And I forgot to update the Readme to reflect that. Sorry.

Sooner or later, I will test if the build facilities could be restored without increasing the image size too much.

**Comment by enriqueartal** [comment]
Thanks for the quick answer. Is there a(n slower)  alternative allowing installation? At some point it worked with conda.

**Comment by kwankyu** [comment]
The "lab" branch is the old sage install based on conda. I didn't touch that and won't.

**Comment by kwankyu** [comment]
This sage-binder-env perhaps won't support package installation ever.

If you want a custom Dockerfile for Binder where the command `RUN /sage/sage -i sirocco` works, you may experiment with

[.github/workflows/binder-dockerfile](https://github.com/sagemath/sage/pull/36245/files)

**Comment by kwankyu** [comment]
I updated the REAME which misguided you.

**Comment by enriqueartal** [comment]
- I managed some time ago to make it work with conda, but I do not remember how. The binder page starts even faster than yours, with version 10.2rc5 ...

That's a good news. If so, someday sage-binder-env may be switched back to conda-based.

- I am playing with the file you pointed in a previous message. It is recompiling the whole system. Is there a way to save the image?

It should not. I don't know. It may be a problem of our build system. I will investigate later.

Thanks for experimenting.

**Comment by enriqueartal** [comment]
Finally, I managed to use conda (actually I had not updated the Readme); it is a little bit slower than your approach but it is useful. Thanks, Enrique.

**Comment by kwankyu** [comment]
Would you share your conda-based script? You may open a PR. Then I could consult your script to update "lab" branch. I cannot work on it right now, but someday I could.

**Comment by enriqueartal** [comment]
I will try to open a PR. Till then, I add an `environment.yml` file in my recent [repo](https://github.com/enriqueartal/SymplecticOctics), basically copied from an [older one](https://github.com/enriqueartal/TorsionDivisorsCubicZariskiPairs). At the time, It was done thanks to the material in this repository and the help of @saraedum (Julian Rüth) and @isuruf (Fernando Isuru). I noticed some changes from this time. For example, I needed to add only `sagemath-sirocco` in the `environment.yml`, and now I should add also `sirocco`. It is also flexible, I started with a smaller distribution, but I got errors in my notebooks for plottings, the error messages pointed that `matplotlib` was missing; it was enough to add it again.

**Comment by kwankyu** [comment]
Thanks. That is very simple. I will experiment with it later.

**Comment by saraedum** [comment]
@enriqueartal you should replace `matplotlib` with `matplotlib-base`. `matplotlib` is a graphical frontend for the library so it also install the matplotlib library itself but you don't need that graphical frontend (most likely.)

**Comment by enriqueartal** [comment]
Thanks, for my purpose matplotlib-base is enough and it saves time.
