### ISSUE TITLE
ThreeJS and JSMol nbextensions give 404

### ISSUE THREAD

**Issue by defeo** [sagemath/sage-binder-env#5]
Reported by @marcinofulus. When plotting in 3d, these urls (and possibly more) give 404s:

- `/hub/nbextensions/threejs/three.min.js`
- `/hub/nbextensions/threejs/OrbitControls.js`
- '/hub/nbextensions/jsmol/JSmol.min.js`

The files seem to be correctly symlinked in `/home/sage/sage/local/share/jupyter/nbextensions/`, I haven't had time to debug yet.

ThreeJS seems to have the same problem in the SageMath version packaged for Debian/Ubuntu (JSmol is not available in Debian).

**Comment by dimpase** [comment]
outdated?

**Comment by kwankyu** [comment]
threejs works well now. Try
```
x, y = var('x y')
W = plot3d(sin(pi*((x)^2 + (y)^2))/2, (x, -1, 1), (y, -1, 1),
           frame=False, color='purple', opacity=0.8)
S = sphere((0, 0, 0), size=0.3, color='red', aspect_ratio=[1,1,1])
show(W + S, viewer="threejs")
```
Of course, threejs is the default viewer now.
