### ISSUE TITLE
Available Kernels

### ISSUE THREAD

**Issue by ingodahn** [sagemath/sage-binder-env#8]
I note that I can use SageMath 8.9, and request it in Dockerfile to run a notebook from CoCalc, but then the user still has to manually select the kernel on binder launch. I did not find out how to launch a notebook with octave kernel.

It might be useful to desccribe in ReadMe what are the available kernels and how they are to be requested in Dockerfile

**Comment by kwankyu** [comment]
Currently, this repo has only sagemath kernel. In my opinion, it should not care about other kernels.

Instead fork this repo, edit the Dockerfile up to your needs. There is a single line for installing sagemath kernel. You may mimic the line for octave kernel. Perhaps you may consult here

https://github.com/Calysto/octave_kernel

to find where the octave kernel is defined.
