### ISSUE TITLE
mybinder.org sagemath does not work any more

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage-binder-env#9]
https://mybinder.org/v2/gh/sagemath/more-sagemath-tutorials/master?filepath=_build/html/tutorial-start-here.ipynb

errors out.

**Comment by mmosmond** [comment]
It seems like this is still/again an issue? My SageMath notebooks via mybinder are also failing over at https://github.com/mmosmond/eeb430. Any ideas what is going on? Everything was working fine in early September but stopped working later in the month. Some updates have broken things? See also https://github.com/calculuslab/Calculus_Lab/issues/1

**Comment by dimpase** [comment]
IMHO it's not us, it's mybinder that's guilty here. Maybe @betatim knows...

**Comment by betatim** [comment]
Have a look at https://github.com/jupyterhub/binderhub/issues/1409#issuecomment-937839234 and the forum threads. It seems likely that this is because of the recent changes to use jupyterlab by default on mybinder.org.

**Comment by behackl** [comment]
While there is a conda-based approach for SageMath + mybinder by now, I still wonder what exactly it is that causes mybinder to fail starting the environment when using a simple Dockerfile like
```
FROM sagemath/sagemath:9.7
COPY --chown=sage:sage . .
```
I played around with the setup a bit and found something somewhat odd: if we don't use the jupyter / notebook installed to SageMath's venv, but instead install Python 3 and `notebook` separately, it *is* possible to use the Docker image: with the Dockerfile provided at https://gist.github.com/behackl/a5d25c901ec557565f99331b130f09a2 (apologies, it's not particularly pretty) the mybinder environment does start up normally and the kernel works as expected (as far as I could tell): [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/behackl/a5d25c901ec557565f99331b130f09a2/HEAD)

Why? Is there some notebook setting that is overwritten or changed in our venv that clashes with how mybinder creates the environment? I'll also share this with sage-devel, perhaps someone has an idea about this. (Edit: [done.](https://groups.google.com/g/sage-devel/c/eQWhQy_Zv08/m/I2Yv1D-jBgAJ))

**Comment by dimpase** [comment]
IMHO Sage should not vendor Jupyter in the 1st place. 

Note that even  not vendoring gcc is still open, cf https://trac.sagemath.org/ticket/32532 - where I propose the remove the capacity to build gcc, retaining the capacity to build gfortran.

**Comment by behackl** [comment]
> IMHO Sage should not vendor Jupyter in the 1st place.

It is nice that `sage -n jupyter` *just works*, but I am not sure whether it is necessary to actually vendor `notebook` for that. I suppose it might be possible for sage to do something intelligent regarding looking for Jupyter installed on the system side and linking its kernel to it, but if it isn't it could still be installed in Sage's venv.

My best guess at this point is that either Sage ships with some specific setting that makes the notebook server unresponsive when started by mybinder (none of [the settings](https://github.com/sagemath/sage/blob/develop/build/pkgs/notebook/jupyter_notebook_config.py) feel like they could be responsible though; but that's something that could be tested) -- or mybinder is not happy with its bash commands being executed via `sage -sh -c`.


> Note that even not vendoring gcc is still open, cf https://trac.sagemath.org/ticket/32532 - where I propose the remove the capacity to build gcc, retaining the capacity to build gfortran.

I'm not familiar with the build toolchain well enough to make a meaningful comment about it, but I don't find it unlikely that this discussion might be easier with packages that have a little less, well, *gravitas*.

**Comment by dimpase** [comment]
fixed by #16
